apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- sa.yaml
- svc.yaml
images:
- name: nginx
  newTag: stable

#replicas:
#- name: nginx
#  count: 4
patches:
- path: patch-deployment.yaml
  target:
    kind: Deployment
    name: nginx
#- patch: |-
#    - op: add
#      path: "/spec/template/spec/containers/0/env/-"
#      value:
#        name: TZ
#        value: "Asia/Singapore"
#  target:
#   kind: Deployment
#    name: nginx