apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: nginx
        env: 
        - name: TZ
          value: "Asia/Singapore"
        - name: config
          valueFrom:
            configMapRef:
              name: nginx-tz

              
