apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: nginx
        env: 
        - name: TZ
          value: "Asia/Singapore"
        envFrom:
        - configMapRef:
            name: nginx-tz
        volumeMounts:
        - mountPath: "/etc/secrets"
          name: nginx-secrets
      volumes:
      - name: nginx-secrets
        secret:
          secretName: nginx-secrets

              
